[build]
  base = "hrms-app"
  command = "npm ci --workspaces && npm run -w frontend-ui-monorepo build"
  publish = "apps/frontend-ui-monorepo/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200