export const attendanceMockData = [
  {
    id: 1,
    name: "Jaydeep Sharma",
    avatar: "",
    designation: "HR Manager",
    location: "Gurugram",
    checkIn: "09:02 AM",
    status: "Present",
  },
  {
    id: 2,
    name: "Yudhvir Singh",
    avatar: "",
    designation: "Graphic Designer",
    location: "Noida",
    checkIn: "09:18 AM",
    status: "Late",
  },
  {
    id: 3,
    name: "Vaishali Verma",
    avatar: "",
    designation: "Project Manager",
    location: "Gurugram",
    checkIn: "—",
    status: "Absent",
  },
  {
    id: 4,
    name: "Debjoyti Das",
    avatar: "",
    designation: "Accountant",
    location: "Kolkata",
    checkIn: "09:05 AM",
    status: "Present",
  },
  {
    id: 5,
    name: "Deepak Kumar",
    avatar: "",
    designation: "Procurement Officer",
    location: "Delhi",
    checkIn: "09:41 AM",
    status: "Late",
  },
  {
    id: 6,
    name: "Prince Yadav",
    avatar: "",
    designation: "Brand Manager",
    location: "Remote",
    checkIn: "08:58 AM",
    status: "Present",
  },

  /* ---------- extra rows for scroll ---------- */

  {
    id: 7,
    name: "Aman Gupta",
    avatar: "",
    designation: "Frontend Engineer",
    location: "Remote",
    checkIn: "09:10 AM",
    status: "Present",
  },
  {
    id: 8,
    name: "Rahul Mehta",
    avatar: "",
    designation: "Backend Engineer",
    location: "Gurugram",
    checkIn: "09:35 AM",
    status: "Late",
  },
  {
    id: 9,
    name: "Mohit Jain",
    avatar: "",
    designation: "QA Engineer",
    location: "Noida",
    checkIn: "—",
    status: "Absent",
  },
  {
    id: 10,
    name: "Ravi Shankar",
    avatar: "",
    designation: "Tech Lead",
    location: "Bangalore",
    checkIn: "08:55 AM",
    status: "Present",
  },
  {
    id: 11,
    name: "Yashoda Nair",
    avatar: "",
    designation: "HR Executive",
    location: "Mumbai",
    checkIn: "09:07 AM",
    status: "Present",
  },
  {
    id: 12,
    name: "Neha Kapoor",
    avatar: "",
    designation: "UI Designer",
    location: "Remote",
    checkIn: "09:22 AM",
    status: "Late",
  },
  {
    id: 13,
    name: "Saurabh Mishra",
    avatar: "",
    designation: "DevOps Engineer",
    location: "Pune",
    checkIn: "08:59 AM",
    status: "Present",
  },
  {
    id: 14,
    name: "Anjali Singh",
    avatar: "",
    designation: "Content Strategist",
    location: "Delhi",
    checkIn: "—",
    status: "Absent",
  },
  {
    id: 15,
    name: "Kunal Verma",
    avatar: "",
    designation: "Product Manager",
    location: "Gurugram",
    checkIn: "09:03 AM",
    status: "Present",
  },
];
